// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // إعدادات Firebase الخاصة بالويب
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // إعدادات Firebase لنظام Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAL36zxCwcQ-fmUuYeSd9SvS9PasPzmRI',
    appId: '1:534313582150:android:39c7429cfcfab33a579447',
    messagingSenderId: '534313582150',
    projectId: 'ahmed-36258',
    storageBucket: 'ahmed-36258.firebasestorage.app',
  );

  // إعدادات Firebase لنظام iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjeqYUJQ4La30nkA15lg7wXysHS4GB1fM',
    appId: '1:534313582150:ios:dc2f753310b80c81579447',
    messagingSenderId: '534313582150',
    projectId: 'ahmed-36258',
    storageBucket: 'ahmed-36258.firebasestorage.app',
    androidClientId:'534313582150-5u0j4q18lkqoj8ln1eu8njv5id082s5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterApk',
  );

  // إعدادات Firebase الخاصة بالويب
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjeqYUJQ4La30nkA15lg7wXysHS4GB1fM',
    appId: '1:534313582150:web:dc2f753310b80c81579447',
    messagingSenderId: '534313582150',
    projectId: 'ahmed-36258',
    storageBucket: 'ahmed-36258.firebasestorage.app',
  );
}
